Repository cc-tweaked/CC-Tweaked, pull requests merged in 2019-06, with the labels that each got.

#225 Add more MOTD messages.
  src/main/resources/assets/computercraft/lua/rom/motd.txt
Labels: enhancement

#226 Add Checks for Turtle and Pocket programs
  src/main/resources/assets/computercraft/lua/rom/programs/pocket/equip.lua
  src/main/resources/assets/computercraft/lua/rom/programs/pocket/unequip.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/craft.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/dance.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/equip.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/excavate.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/go.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/refuel.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/tunnel.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/turn.lua
  src/main/resources/assets/computercraft/lua/rom/programs/turtle/unequip.lua
Labels: enhancement

#236 Add Check to delete.lua (Update)
  src/main/resources/assets/computercraft/lua/rom/programs/delete.lua
  src/test/resources/test-rom/spec/programs/delete_spec.lua
Labels: area-CraftOS, enhancement

#235 Fix some warnings
  .gitignore
  src/main/java/dan200/computercraft/api/filesystem/IMount.java
  src/main/java/dan200/computercraft/api/filesystem/IWritableMount.java
  src/main/java/dan200/computercraft/core/apis/HTTPAPI.java
  src/main/java/dan200/computercraft/core/apis/OSAPI.java
  src/main/java/dan200/computercraft/core/apis/PeripheralAPI.java
  src/main/java/dan200/computercraft/core/computer/Computer.java
  src/main/java/dan200/computercraft/core/filesystem/JarMount.java
  src/main/java/dan200/computercraft/shared/common/BlockGeneric.java
  src/main/java/dan200/computercraft/shared/common/TileGeneric.java
  src/main/java/dan200/computercraft/shared/computer/core/ServerComputer.java
  src/main/java/dan200/computercraft/shared/integration/jei/JEIComputerCraft.java
  src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPeripheral.java
  src/main/java/dan200/computercraft/shared/turtle/core/TurtlePlaceCommand.java
  src/main/java/dan200/computercraft/shared/util/StringUtil.java
  src/test/java/dan200/computercraft/shared/wired/NetworkTest.java
Labels: enhancement

#218 Add webrun
  src/main/resources/assets/computercraft/lua/rom/help/wget.txt
  src/main/resources/assets/computercraft/lua/rom/motd.txt
  src/main/resources/assets/computercraft/lua/rom/programs/http/wget.lua
  src/main/resources/assets/computercraft/lua/rom/startup.lua
  src/test/resources/test-rom/spec/http/wget_spec.lua
Labels: area-CraftOS, enhancement, feedback wanted

#246 Fix Bug in rename.lua
  src/main/resources/assets/computercraft/lua/rom/programs/rename.lua
  src/test/resources/test-rom/spec/programs/rename_spec.lua
Labels: area-CraftOS, enhancement

#247 Add Checks to copy.lua
  src/main/resources/assets/computercraft/lua/rom/programs/copy.lua
  src/test/resources/test-rom/spec/programs/copy_spec.lua
Labels: area-CraftOS, enhancement

#248 Add a few Checks
  src/test/resources/test-rom/mcfly.lua
  src/test/resources/test-rom/spec/programs/cd_spec.lua
  src/test/resources/test-rom/spec/programs/edit_spec.lua
  src/test/resources/test-rom/spec/programs/http/pastebin_spec.lua
  src/test/resources/test-rom/spec/programs/http/wget_spec.lua
  src/test/resources/test-rom/spec/programs/id_spec.lua
  src/test/resources/test-rom/spec/programs/motd_spec.lua
  src/test/resources/test-rom/spec/programs/move_spec.lua
  src/test/resources/test-rom/spec/programs/set_spec.lua
  src/test/resources/test-rom/spec/programs/shell_spec.lua
  src/test/resources/test-rom/spec/programs/time_spec.lua
  src/test/resources/test-rom/spec/programs/type_spec.lua
Labels: area-CraftOS

#259 Change URLs in build.gradle to https
  build.gradle
Labels: enhancement
