Repository cc-tweaked/CC-Tweaked, pull requests merged in 2019-12, with the labels that each got.

#327 Basic CraftTweaker support
  build.gradle
  src/main/java/dan200/computercraft/shared/TurtleUpgrades.java
  src/main/java/dan200/computercraft/shared/integration/crafttweaker/TurtleTweaker.java
  src/main/java/dan200/computercraft/shared/integration/crafttweaker/actions/AddTurtleTool.java
  src/main/java/dan200/computercraft/shared/integration/crafttweaker/actions/IAction.java
  src/main/java/dan200/computercraft/shared/integration/crafttweaker/actions/RemoveTurtleUpgradeByItem.java
  src/main/java/dan200/computercraft/shared/integration/crafttweaker/actions/RemoveTurtleUpgradeByName.java
  src/main/java/dan200/computercraft/shared/turtle/items/ItemTurtleBase.java
  src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleAxe.java
  src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleHoe.java
  src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleShovel.java
  src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleSword.java
  src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleTool.java
Labels: area-Minecraft, enhancement

#241 Add more MOTD messages again
  src/main/resources/assets/computercraft/lua/rom/motd.txt
Labels: area-CraftOS, enhancement

#331 wilcards > wildcards
  src/main/java/dan200/computercraft/shared/Config.java
Labels: area-Minecraft, bug
