Repository cc-tweaked/CC-Tweaked, pull requests merged in 2019-07, with the labels that each got.

#253 Add more tests
  .luacheckrc
  src/test/resources/test-rom/mcfly.lua
  src/test/resources/test-rom/spec/programs/advanced/bg_spec.lua
  src/test/resources/test-rom/spec/programs/advanced/fg_spec.lua
  src/test/resources/test-rom/spec/programs/alias_spec.lua
  src/test/resources/test-rom/spec/programs/cd_spec.lua
  src/test/resources/test-rom/spec/programs/clear_spec.lua
  src/test/resources/test-rom/spec/programs/command/commands_spec.lua
  src/test/resources/test-rom/spec/programs/command/exec_spec.lua
  src/test/resources/test-rom/spec/programs/drive_spec.lua
  src/test/resources/test-rom/spec/programs/edit_spec.lua
  src/test/resources/test-rom/spec/programs/eject_spec.lua
  src/test/resources/test-rom/spec/programs/exit_spec.lua
  src/test/resources/test-rom/spec/programs/fun/advanced/paint_spec.lua
  src/test/resources/test-rom/spec/programs/fun/dj_spec.lua
  src/test/resources/test-rom/spec/programs/fun/hello_spec.lua
  src/test/resources/test-rom/spec/programs/gps_spec.lua
  src/test/resources/test-rom/spec/programs/help_spec.lua
  src/test/resources/test-rom/spec/programs/label_spec.lua
  src/test/resources/test-rom/spec/programs/list_spec.lua
  src/test/resources/test-rom/spec/programs/monitor_spec.lua
  src/test/resources/test-rom/spec/programs/peripherals_spec.lua
  src/test/resources/test-rom/spec/programs/pocket/equip_spec.lua
  src/test/resources/test-rom/spec/programs/pocket/unequip_spec.lua
  src/test/resources/test-rom/spec/programs/programs_spec.lua
  src/test/resources/test-rom/spec/programs/reboot_spec.lua
  src/test/resources/test-rom/spec/programs/redstone_spec.lua
  src/test/resources/test-rom/spec/programs/shutdown_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/craft_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/equip_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/refuel_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/unequip_spec.lua
Labels: area-CraftOS

#267 Expose expect as a module
  src/main/resources/assets/computercraft/lua/bios.lua
  src/main/resources/assets/computercraft/lua/rom/apis/colors.lua
  src/main/resources/assets/computercraft/lua/rom/apis/gps.lua
  src/main/resources/assets/computercraft/lua/rom/apis/help.lua
  src/main/resources/assets/computercraft/lua/rom/apis/io.lua
  src/main/resources/assets/computercraft/lua/rom/apis/keys.lua
  src/main/resources/assets/computercraft/lua/rom/apis/paintutils.lua
  src/main/resources/assets/computercraft/lua/rom/apis/peripheral.lua
  src/main/resources/assets/computercraft/lua/rom/apis/rednet.lua
  src/main/resources/assets/computercraft/lua/rom/apis/settings.lua
  src/main/resources/assets/computercraft/lua/rom/apis/term.lua
  src/main/resources/assets/computercraft/lua/rom/apis/textutils.lua
  src/main/resources/assets/computercraft/lua/rom/apis/window.lua
  src/main/resources/assets/computercraft/lua/rom/modules/main/craftos/expect.lua
  src/main/resources/assets/computercraft/lua/rom/programs/advanced/multishell.lua
  src/main/resources/assets/computercraft/lua/rom/programs/shell.lua
  src/test/resources/test-rom/spec/base_spec.lua
  src/test/resources/test-rom/spec/modules/expect_spec.lua
Labels: area-CraftOS, enhancement

#272 Add term.getLine and window.getLine
  src/main/java/dan200/computercraft/core/apis/TermAPI.java
  src/test/resources/test-rom/spec/apis/term_spec.lua
Labels: area-CraftOS, enhancement

#276 Fixed turtle cable duping
  src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleTool.java
Labels: area-Minecraft, bug

#274 Fixed fuel issue
  src/main/java/dan200/computercraft/shared/turtle/FurnaceRefuelHandler.java
Labels: area-Minecraft, bug
