Repository cc-tweaked/CC-Tweaked, pull requests merged in 2020-01, with the labels that each got.

#332 Make builded Jar downloadable
  .github/workflows/main-ci.yml
Labels: enhancement

#341 Anonymized GPS
  src/main/resources/assets/computercraft/lua/rom/apis/gps.lua
Labels: area-CraftOS, enhancement, feedback wanted

#334 Use a Wadler style pretty printer in the Lua REPL
  src/main/resources/assets/computercraft/lua/rom/modules/main/cc/pretty.lua
  src/main/resources/assets/computercraft/lua/rom/programs/lua.lua
  src/test/resources/test-rom/spec/modules/cc/pretty_spec.lua
Labels: area-CraftOS, enhancement, feedback wanted

#350 fix models
  src/main/resources/assets/computercraft/models/block/modem.json
  src/main/resources/assets/computercraft/models/block/turtle_base.json
  src/main/resources/assets/computercraft/models/block/turtle_upgrade_base_left.json
  src/main/resources/assets/computercraft/models/block/turtle_upgrade_base_right.json
  src/main/resources/assets/computercraft/models/block/turtle_white.json
Labels: area-Minecraft, bug
