Repository cc-tweaked/CC-Tweaked, pull requests merged in 2020-10, with the labels that each got.

#549 Don't propagate adjacent redstone signals for computers
  src/main/java/dan200/computercraft/shared/computer/blocks/BlockComputerBase.java
Labels: area-Minecraft, enhancement, feedback wanted

#553 Add color table to docs
  doc/styles.css
  src/main/resources/data/computercraft/lua/rom/apis/colors.lua
Labels: area-CraftOS, enhancement

#556 Update illuaminate CSS for deprecation
  doc/styles.css
Labels: enhancement

#560 Fix TBO normalisation issues on old GPUs
  src/main/java/dan200/computercraft/shared/peripheral/monitor/ClientMonitor.java
  src/main/resources/assets/computercraft/shaders/monitor.frag
Labels: area-Minecraft, enhancement
