Repository cc-tweaked/CC-Tweaked, pull requests merged in 2020-11, with the labels that each got.

#570 Use blit to draw boxes, add colors.toBlit
  src/main/resources/data/computercraft/lua/rom/apis/colors.lua
  src/main/resources/data/computercraft/lua/rom/apis/paintutils.lua
  src/test/resources/test-rom/spec/apis/colors_spec.lua
  src/test/resources/test-rom/spec/apis/paintutils_spec.lua
Labels: area-CraftOS, enhancement

#571 use arg[0] in all usage printouts
  src/main/resources/data/computercraft/lua/rom/programs/alias.lua
  src/main/resources/data/computercraft/lua/rom/programs/cd.lua
  src/main/resources/data/computercraft/lua/rom/programs/command/exec.lua
  src/main/resources/data/computercraft/lua/rom/programs/copy.lua
  src/main/resources/data/computercraft/lua/rom/programs/delete.lua
  src/main/resources/data/computercraft/lua/rom/programs/edit.lua
  src/main/resources/data/computercraft/lua/rom/programs/eject.lua
  src/main/resources/data/computercraft/lua/rom/programs/fun/advanced/paint.lua
  src/main/resources/data/computercraft/lua/rom/programs/fun/dj.lua
  src/main/resources/data/computercraft/lua/rom/programs/gps.lua
  src/main/resources/data/computercraft/lua/rom/programs/http/pastebin.lua
  src/main/resources/data/computercraft/lua/rom/programs/http/wget.lua
  src/main/resources/data/computercraft/lua/rom/programs/label.lua
  src/main/resources/data/computercraft/lua/rom/programs/mkdir.lua
  src/main/resources/data/computercraft/lua/rom/programs/monitor.lua
  src/main/resources/data/computercraft/lua/rom/programs/move.lua
  src/main/resources/data/computercraft/lua/rom/programs/rednet/chat.lua
  src/main/resources/data/computercraft/lua/rom/programs/redstone.lua
  src/main/resources/data/computercraft/lua/rom/programs/rename.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/craft.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/equip.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/excavate.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/go.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/refuel.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/tunnel.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/turn.lua
  src/main/resources/data/computercraft/lua/rom/programs/turtle/unequip.lua
  src/main/resources/data/computercraft/lua/rom/programs/type.lua
  src/test/resources/test-rom/spec/programs/command/exec_spec.lua
  src/test/resources/test-rom/spec/programs/copy_spec.lua
  src/test/resources/test-rom/spec/programs/move_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/craft_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/equip_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/refuel_spec.lua
  src/test/resources/test-rom/spec/programs/turtle/unequip_spec.lua
Labels: area-CraftOS, enhancement

#576 POC for runnable examples
  .editorconfig
  .github/workflows/make-doc.sh
  .github/workflows/make-doc.yml
  .gitignore
  build.gradle
  doc/styles.css
  illuaminate.sexp
  package-lock.json
  package.json
  rollup.config.js
  src/web/copy-cat.d.ts
  src/web/index.tsx
  src/web/mount/.settings
  src/web/mount/expr_template.lua
  src/web/mount/startup.lua
  src/web/styles.css
  tools/check-lines.py
  tsconfig.json
Labels: area-Documentation, enhancement

#580 epoch not represented in seconds as per the docs
  src/main/java/dan200/computercraft/core/apis/OSAPI.java
Labels: area-CraftOS, area-Documentation, bug

#582 Clear gets an option to reset the palette
  src/main/resources/data/computercraft/lua/rom/help/clear.txt
  src/main/resources/data/computercraft/lua/rom/programs/clear.lua
  src/main/resources/data/computercraft/lua/rom/startup.lua
Labels: area-CraftOS, enhancement

#583 Strict Globals
  src/main/resources/data/computercraft/lua/bios.lua
Labels: area-CraftOS, enhancement

#586 Remove extra space
  src/main/resources/data/computercraft/lua/bios.lua
Labels: area-CraftOS, bug

#589 Fixed length check on function name in `expect`
  src/main/resources/data/computercraft/lua/rom/modules/main/cc/expect.lua
Labels: area-CraftOS, bug

#592 Added documentation for global functions
  doc/stub/global.lua
  src/main/java/dan200/computercraft/shared/turtle/apis/TurtleAPI.java
Labels: area-CraftOS, area-Documentation, enhancement
