Repository cc-tweaked/CC-Tweaked, pull requests merged in 2020-07, with the labels that each got.

#491 Add port to Host http header if necessary
  src/main/java/dan200/computercraft/core/apis/http/request/HttpRequestHandler.java
Labels: area-Core, enhancement

#490 Added Javadoc for currently undocumented functions
  src/main/java/dan200/computercraft/core/apis/FSAPI.java
  src/main/java/dan200/computercraft/core/apis/OSAPI.java
  src/main/java/dan200/computercraft/shared/peripheral/diskdrive/DiskDrivePeripheral.java
  src/main/java/dan200/computercraft/shared/peripheral/printer/PrinterPeripheral.java
  src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPeripheral.java
Labels: enhancement

#488 Add enchantments and unbreakable to ItemData.java.
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/BlockData.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/DataHelpers.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/FluidData.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/ItemData.java
Labels: area-Minecraft, enhancement

#508 Fix JSON serialization of strings
  src/main/resources/data/computercraft/lua/rom/apis/textutils.lua
  src/test/resources/test-rom/spec/apis/textutils_spec.lua
Labels: area-CraftOS, bug

#512 Make the key for mtime "modified" in fs.attributes
  src/main/java/dan200/computercraft/core/apis/FSAPI.java
  src/test/resources/test-rom/spec/apis/fs_spec.lua
Labels: area-Core, bug
