Repository cc-tweaked/CC-Tweaked, pull requests merged in 2020-05, with the labels that each got.

#436 Return the peripheral name when wrapping
  src/main/resources/assets/computercraft/lua/rom/apis/peripheral.lua
  src/main/resources/assets/computercraft/lua/rom/help/peripheral.txt
  src/test/resources/test-rom/spec/apis/peripheral_spec.lua
Labels: area-CraftOS, enhancement

#437 Preserve computer ids on unlabelled computers
  src/main/java/dan200/computercraft/shared/computer/blocks/BlockComputerBase.java
  src/main/java/dan200/computercraft/shared/computer/items/ComputerItemFactory.java
  src/main/java/dan200/computercraft/shared/computer/items/ItemComputerBase.java
  src/main/java/dan200/computercraft/shared/media/items/ItemDiskLegacy.java
  src/main/java/dan200/computercraft/shared/pocket/items/ItemPocketComputer.java
  src/main/java/dan200/computercraft/shared/turtle/items/TurtleItemFactory.java
  src/main/resources/assets/computercraft/lang/da_dk.lang
  src/main/resources/assets/computercraft/lang/de_de.lang
  src/main/resources/assets/computercraft/lang/en_us.lang
  src/main/resources/assets/computercraft/lang/ko_kr.lang
  src/main/resources/assets/computercraft/lang/zh_cn.lang
Labels: area-Minecraft, enhancement, feedback wanted

#443 Add a monitor renderer using TBOs
  src/main/java/dan200/computercraft/client/gui/FixedWidthFontRenderer.java
  src/main/java/dan200/computercraft/client/render/MonitorTextureBufferShader.java
  src/main/java/dan200/computercraft/client/render/TileEntityMonitorRenderer.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/ClientMonitor.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/MonitorRenderer.java
  src/main/resources/assets/computercraft/lang/en_us.lang
  src/main/resources/assets/computercraft/shaders/monitor.frag
  src/main/resources/assets/computercraft/shaders/monitor.vert
Labels: area-Minecraft, enhancement, version-1.12.x

#367 Allow lua REPL to warn about using local variables
  src/main/resources/assets/computercraft/lua/bios.lua
  src/main/resources/assets/computercraft/lua/rom/programs/lua.lua
Labels: area-CraftOS, enhancement, feedback wanted

#453 Rewrite monitor networking
  src/main/java/dan200/computercraft/ComputerCraft.java
  src/main/java/dan200/computercraft/core/apis/handles/HandleGeneric.java
  src/main/java/dan200/computercraft/core/apis/http/Resource.java
  src/main/java/dan200/computercraft/core/apis/http/websocket/Websocket.java
  src/main/java/dan200/computercraft/core/filesystem/FileSystem.java
  src/main/java/dan200/computercraft/shared/Config.java
  src/main/java/dan200/computercraft/shared/common/ClientTerminal.java
  src/main/java/dan200/computercraft/shared/common/ServerTerminal.java
  src/main/java/dan200/computercraft/shared/computer/core/ServerComputer.java
  src/main/java/dan200/computercraft/shared/network/NetworkHandler.java
  src/main/java/dan200/computercraft/shared/network/client/ComputerTerminalClientMessage.java
  src/main/java/dan200/computercraft/shared/network/client/MonitorClientMessage.java
  src/main/java/dan200/computercraft/shared/network/client/TerminalState.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/MonitorWatcher.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/TileMonitor.java
  src/main/java/dan200/computercraft/shared/util/IoUtil.java
  src/main/resources/assets/computercraft/lang/en_us.lang
  src/test/java/dan200/computercraft/shared/network/client/TerminalStateTest.java
Labels: area-Minecraft, enhancement

#454 Simplify monitor TBO shader
  src/main/java/dan200/computercraft/client/render/MonitorTextureBufferShader.java
  src/main/resources/assets/computercraft/shaders/monitor.vert
Labels: area-Minecraft, enhancement

#459 Oops! No standards compliance
  src/main/resources/assets/computercraft/shaders/monitor.vert
Labels: area-Minecraft, bug
