Repository cc-tweaked/CC-Tweaked, pull requests merged in 2020-04, with the labels that each got.

#395 Add Danish translation
  src/main/resources/assets/computercraft/lang/da_dk.lang
Labels: area-Minecraft, enhancement

#381 Create ko_kr.lang
  src/main/resources/assets/computercraft/lang/ko_kr.lang
Labels: area-Minecraft, enhancement

#360 An initial stab at documentation generation
  .editorconfig
  .github/workflows/make-doc.sh
  .github/workflows/make-doc.yml
  .gitignore
  README.md
  doc/index.md
  doc/logo.png
  doc/stub/commands.lua
  doc/stub/fs.lua
  doc/stub/http.lua
  doc/stub/os.lua
  doc/stub/redstone.lua
  doc/stub/term.lua
  doc/stub/turtle.lua
  doc/styles.css
  illuaminate.sexp
  src/main/resources/assets/computercraft/lua/bios.lua
  src/main/resources/assets/computercraft/lua/rom/apis/colors.lua
  src/main/resources/assets/computercraft/lua/rom/apis/colours.lua
  src/main/resources/assets/computercraft/lua/rom/apis/command/commands.lua
  src/main/resources/assets/computercraft/lua/rom/apis/disk.lua
  src/main/resources/assets/computercraft/lua/rom/apis/gps.lua
  src/main/resources/assets/computercraft/lua/rom/apis/help.lua
  src/main/resources/assets/computercraft/lua/rom/apis/io.lua
  src/main/resources/assets/computercraft/lua/rom/apis/keys.lua
  src/main/resources/assets/computercraft/lua/rom/apis/paintutils.lua
  src/main/resources/assets/computercraft/lua/rom/apis/parallel.lua
  src/main/resources/assets/computercraft/lua/rom/apis/peripheral.lua
  src/main/resources/assets/computercraft/lua/rom/apis/rednet.lua
  src/main/resources/assets/computercraft/lua/rom/apis/settings.lua
  src/main/resources/assets/computercraft/lua/rom/apis/term.lua
  src/main/resources/assets/computercraft/lua/rom/apis/textutils.lua
  src/main/resources/assets/computercraft/lua/rom/apis/turtle/turtle.lua
  src/main/resources/assets/computercraft/lua/rom/apis/vector.lua
  src/main/resources/assets/computercraft/lua/rom/apis/window.lua
  src/main/resources/assets/computercraft/lua/rom/modules/main/cc/expect.lua
  src/main/resources/assets/computercraft/lua/rom/modules/main/cc/pretty.lua
  src/test/resources/test-rom/mcfly.lua
  src/test/resources/test-rom/spec/modules/cc/pretty_spec.lua
Labels: area-CraftOS, enhancement, feedback wanted, good first issue, help wanted

#412 Backport 1.15's terminal rendering code
  src/main/java/dan200/computercraft/ComputerCraft.java
  src/main/java/dan200/computercraft/client/gui/FixedWidthFontRenderer.java
  src/main/java/dan200/computercraft/client/gui/widgets/WidgetTerminal.java
  src/main/java/dan200/computercraft/client/render/ItemPocketRenderer.java
  src/main/java/dan200/computercraft/client/render/PrintoutRenderer.java
  src/main/java/dan200/computercraft/client/render/TileEntityMonitorRenderer.java
  src/main/java/dan200/computercraft/shared/Config.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/ClientMonitor.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/MonitorRenderer.java
  src/main/java/dan200/computercraft/shared/util/Palette.java
  src/main/resources/assets/computercraft/lang/en_us.lang
  src/main/resources/assets/computercraft/textures/gui/term_background.png
  src/main/resources/assets/computercraft/textures/gui/term_font.png
Labels: area-Minecraft, enhancement

#408 Some redesigning of the settings API
  src/main/resources/assets/computercraft/lua/bios.lua
  src/main/resources/assets/computercraft/lua/rom/apis/settings.lua
  src/main/resources/assets/computercraft/lua/rom/programs/set.lua
  src/test/resources/test-rom/spec/apis/settings_spec.lua
  src/test/resources/test-rom/spec/programs/set_spec.lua
Labels: area-CraftOS, enhancement, feedback wanted

#418 Fix settings.save() sPath param.
  src/main/resources/assets/computercraft/lua/rom/apis/settings.lua
Labels: area-CraftOS, bug

#410 Remove / and \ at the start of shell.setDir()
  src/main/resources/assets/computercraft/lua/rom/programs/shell.lua
Labels: area-CraftOS, enhancement

#396 Redo how http block/allow lists are stored.
  src/main/java/dan200/computercraft/ComputerCraft.java
  src/main/java/dan200/computercraft/core/apis/AddressPredicate.java
  src/main/java/dan200/computercraft/core/apis/HTTPAPI.java
  src/main/java/dan200/computercraft/core/apis/http/AddressRule.java
  src/main/java/dan200/computercraft/core/apis/http/NetworkUtils.java
  src/main/java/dan200/computercraft/core/apis/http/request/HttpRequest.java
  src/main/java/dan200/computercraft/core/apis/http/websocket/Websocket.java
  src/main/java/dan200/computercraft/core/computer/ComputerExecutor.java
  src/main/java/dan200/computercraft/shared/Config.java
Labels: area-Core, enhancement, feedback wanted

#419 Add mouse support for the menu in edit and paint
  src/main/resources/assets/computercraft/lua/rom/programs/edit.lua
  src/main/resources/assets/computercraft/lua/rom/programs/fun/advanced/paint.lua
Labels: area-CraftOS, enhancement
