Repository cc-tweaked/CC-Tweaked, pull requests merged in 2021-06, with the labels that each got.

#743 Fixed side input consistency issue when a turtle upgrade is removed
  src/main/java/dan200/computercraft/shared/turtle/core/TurtleBrain.java
  src/test/java/dan200/computercraft/ingame/TurtleTest.kt
Labels: area-Minecraft, bug

#807 Make craft without arguments craft as many items as possible.
  src/main/resources/data/computercraft/lua/rom/help/craft.txt
  src/main/resources/data/computercraft/lua/rom/programs/turtle/craft.lua
  src/test/resources/test-rom/spec/programs/turtle/craft_spec.lua
Labels: area-CraftOS, bug

#809 Additional terminal buttons
  src/main/java/dan200/computercraft/client/gui/GuiComputer.java
  src/main/java/dan200/computercraft/client/gui/GuiTurtle.java
  src/main/java/dan200/computercraft/client/gui/widgets/ComputerSidebar.java
  src/main/java/dan200/computercraft/client/gui/widgets/DynamicImageButton.java
  src/main/java/dan200/computercraft/client/gui/widgets/WidgetTerminal.java
  src/main/java/dan200/computercraft/client/gui/widgets/WidgetWrapper.java
  src/main/java/dan200/computercraft/client/render/ComputerBorderRenderer.java
  src/main/java/dan200/computercraft/shared/turtle/inventory/ContainerTurtle.java
  src/main/resources/assets/computercraft/lang/en_us.json
  src/main/resources/assets/computercraft/textures/gui/buttons.png
  src/main/resources/assets/computercraft/textures/gui/corners_advanced.png
  src/main/resources/assets/computercraft/textures/gui/corners_normal.png
Labels: area-Minecraft, enhancement, feedback wanted

#816 Fixed error handling in scale subcommand
  src/main/resources/data/computercraft/lua/rom/programs/monitor.lua
  src/test/resources/test-rom/spec/programs/monitor_spec.lua
Labels: area-CraftOS, bug

#815 Add cc.shell.completion `programWithArgs` completion.
  src/main/resources/data/computercraft/lua/rom/modules/main/cc/shell/completion.lua
  src/main/resources/data/computercraft/lua/rom/startup.lua
  src/test/resources/test-rom/spec/modules/cc/shell/completion_spec.lua
Labels: area-CraftOS, enhancement

#819 Add very simple markdown support to the help viewer
  build.gradle
  src/main/resources/data/computercraft/lua/rom/apis/help.lua
  src/main/resources/data/computercraft/lua/rom/help/changelog.md
  src/main/resources/data/computercraft/lua/rom/help/whatsnew.md
  src/main/resources/data/computercraft/lua/rom/programs/help.lua
  src/test/resources/test-rom/spec/apis/help_spec.lua
Labels: area-CraftOS, enhancement, feedback wanted

#817 Gitpod Support
  .gitpod.yml
  CONTRIBUTING.md
  config/gitpod/Dockerfile
Labels: enhancement

#842 remove extra ,
  src/main/resources/data/computercraft/lua/rom/modules/main/cc/expect.lua
Labels: area-Documentation, bug
