Repository cc-tweaked/CC-Tweaked, pull requests merged in 2021-01, with the labels that each got.

#639 add isReadOnly to fs.attributes
  src/main/java/dan200/computercraft/core/apis/FSAPI.java
  src/test/resources/test-rom/spec/apis/fs_spec.lua
Labels: area-Core, enhancement

#657 Added Numpad Enter Support in rom lua programs.
  src/main/resources/data/computercraft/lua/rom/programs/edit.lua
  src/main/resources/data/computercraft/lua/rom/programs/fun/advanced/paint.lua
  src/main/resources/data/computercraft/lua/rom/programs/fun/worm.lua
  src/main/resources/data/computercraft/lua/rom/programs/pocket/falling.lua
Labels: area-CraftOS, bug

#672 Make rightAlt only close menu, never open it.
  src/main/resources/data/computercraft/lua/rom/programs/edit.lua
Labels: area-Minecraft, bug

#677 Fix/Update id.lua
  src/main/resources/data/computercraft/lua/rom/programs/id.lua
Labels: area-CraftOS, bug

#685 allowing serialisation of arrays with nil values into json.
  src/main/resources/data/computercraft/lua/rom/apis/textutils.lua
  src/test/resources/test-rom/spec/apis/textutils_spec.lua
Labels: area-CraftOS, enhancement

#683 Finish the rest of the event documentation
  doc/events/alarm.md
  doc/events/computer_command.md
  doc/events/disk.md
  doc/events/disk_eject.md
  doc/events/http_check.md
  doc/events/http_failure.md
  doc/events/http_success.md
  doc/events/key.md
  doc/events/modem_message.md
  doc/events/monitor_resize.md
  doc/events/monitor_touch.md
  doc/events/mouse_drag.md
  doc/events/mouse_up.md
  doc/events/paste.md
  doc/events/peripheral.md
  doc/events/peripheral_detach.md
  doc/events/rednet_message.md
  doc/events/redstone.md
  doc/events/task_complete.md
  doc/events/term_resize.md
  doc/events/terminate.md
  doc/events/timer.md
  doc/events/turtle_inventory.md
  doc/events/websocket_closed.md
  doc/events/websocket_failure.md
  doc/events/websocket_message.md
  doc/events/websocket_success.md
Labels: area-Documentation, enhancement
