Repository cc-tweaked/CC-Tweaked, pull requests merged in 2021-09, with the labels that each got.

#924 Fixed typo in the javadoc of CommandsAPI class
  src/main/java/dan200/computercraft/shared/computer/apis/CommandAPI.java
Labels: bug, area-Documentation

#920 Serialize better repetition error and infinity+nan handling.
  src/main/resources/data/computercraft/lua/rom/apis/textutils.lua
  src/test/resources/test-rom/spec/apis/textutils_spec.lua
Labels: area-CraftOS

#918 Allow player world interaction while pocket pc opened with no terminal
  src/main/java/dan200/computercraft/client/gui/NoTermComputerScreen.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, area-Minecraft

#927 Added binary flag to websocket_message docs
  doc/events/websocket_message.md
Labels: area-Documentation

#900 Fix for computer IDs greater than 65535 crashing Rednet
  illuaminate.sexp
  src/main/resources/data/computercraft/lua/rom/apis/rednet.lua
  src/main/resources/data/computercraft/lua/rom/programs/rednet/repeat.lua
  src/test/resources/test-rom/spec/apis/rednet_spec.lua
  src/test/resources/test-rom/spec/support/fake_computer.lua
Labels: bug, area-CraftOS

#925 Make Rednet deduplication more efficient
  src/main/resources/data/computercraft/lua/rom/apis/rednet.lua
  src/test/resources/test-rom/spec/apis/rednet_spec.lua
  src/test/resources/test-rom/spec/support/debug_ext.lua
  src/test/resources/test-rom/spec/support/fake_computer.lua
Labels: enhancement, area-CraftOS
