Repository cc-tweaked/CC-Tweaked, pull requests merged in 2022-11, with the labels that each got.

#1194 Possible fix for issue #1150
  src/main/resources/data/computercraft/lua/bios.lua
  src/main/resources/data/computercraft/lua/rom/modules/main/cc/shell/completion.lua
  src/main/resources/data/computercraft/lua/rom/programs/shell.lua
Labels: enhancement, area-CraftOS

#1200 Check for valid nSender field on RedNet message receive
  src/main/resources/data/computercraft/lua/rom/apis/rednet.lua
Labels: area-CraftOS

#1209 Fixed typo
  src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPeripheral.java
Labels: bug, area-Documentation

#1219 Add a system for client-side tests
  .github/workflows/main-ci.yml
  buildSrc/src/main/kotlin/cc/tweaked/gradle/CCTweakedExtension.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/CheckChangelog.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/CheckLicense.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/Extensions.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/IdeaRunConfigurations.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/MinecraftExec.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/ProcessHelpers.kt
  gradle/libs.versions.toml
  projects/common/src/main/java/dan200/computercraft/shared/platform/Registries.java
  projects/common/src/testMod/java/dan200/computercraft/gametest/api/GameTestHolder.java
  projects/common/src/testMod/java/dan200/computercraft/gametest/core/CCTestCommand.java
  projects/common/src/testMod/java/dan200/computercraft/gametest/core/TestAPI.java
  projects/common/src/testMod/java/dan200/computercraft/gametest/core/TestHooks.java
  projects/common/src/testMod/java/dan200/computercraft/mixin/gametest/GameTestSequenceAccessor.java
  projects/common/src/testMod/java/dan200/computercraft/mixin/gametest/SharedConstantsMixin.java
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Computer_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/CraftOs_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Disk_Drive_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Loot_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Modem_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Monitor_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Printer_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Recipe_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Turtle_Test.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/api/ClientGameTest.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/api/ClientTestExtensions.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/api/TestExtensions.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/api/TestTags.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/core/ClientTestHooks.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/core/TestHooks.kt
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/core/TestReporters.kt
  projects/common/src/testMod/resources/computercraft-gametest.mixins.json
  projects/common/src/testMod/resources/data/cctest/structures/computer_test.open_on_client.snbt
  projects/common/src/testMod/resources/data/cctest/structures/monitor_test.render_monitor.snbt
  projects/fabric/build.gradle.kts
  projects/fabric/src/testMod/java/dan200/computercraft/gametest/core/TestMod.java
  projects/fabric/src/testMod/resources/fabric.mod.json
  projects/forge/build.gradle.kts
  projects/forge/src/testMod/java/dan200/computercraft/gametest/core/ClientHooks.java
  projects/forge/src/testMod/java/dan200/computercraft/gametest/core/TestMod.java
  tools/parse-reports.py
  tools/screenshots.py
Labels: enhancement, area-Minecraft

#1226 Check the filesystem for isReadOnly
  projects/core-api/src/main/java/dan200/computercraft/api/filesystem/IWritableMount.java
  projects/core/src/main/java/dan200/computercraft/core/filesystem/FileMount.java
  projects/core/src/main/java/dan200/computercraft/core/filesystem/FileSystemWrapperMount.java
  projects/core/src/main/java/dan200/computercraft/core/filesystem/MountWrapper.java
  projects/core/src/test/java/dan200/computercraft/core/filesystem/FileMountTest.java
Labels: enhancement, area-Core
