Repository cc-tweaked/CC-Tweaked, pull requests merged in 2022-10, with the labels that each got.

#1182 Add all but 3 of the missing dutch translations
  src/main/resources/assets/computercraft/lang/nl_nl.json
Labels: enhancement, area-Minecraft

#1188 Expose getters for the detail registry too
  src/main/java/dan200/computercraft/ComputerCraftAPIImpl.java
  src/main/java/dan200/computercraft/api/ComputerCraftAPI.java
  src/main/java/dan200/computercraft/api/detail/DetailRegistries.java
  src/main/java/dan200/computercraft/api/detail/DetailRegistry.java
  src/main/java/dan200/computercraft/api/detail/IDetailProvider.java
  src/main/java/dan200/computercraft/impl/ComputerCraftAPIService.java
  src/main/java/dan200/computercraft/impl/detail/DetailRegistryImpl.java
  src/main/java/dan200/computercraft/shared/Registry.java
  src/main/java/dan200/computercraft/shared/computer/apis/CommandAPI.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/BlockData.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/DetailProviders.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/FluidData.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/ItemData.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/methods/FluidMethods.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/methods/InventoryMethods.java
  src/main/java/dan200/computercraft/shared/turtle/apis/TurtleAPI.java
  src/main/java/dan200/computercraft/shared/turtle/core/TurtleInspectCommand.java
  src/testMod/java/dan200/computercraft/ingame/TurtleTest.kt
Labels: enhancement, area-Minecraft

#1189 Rewrite the metrics system
  src/main/java/dan200/computercraft/core/apis/FSAPI.java
  src/main/java/dan200/computercraft/core/apis/IAPIEnvironment.java
  src/main/java/dan200/computercraft/core/apis/PeripheralAPI.java
  src/main/java/dan200/computercraft/core/apis/http/request/HttpRequest.java
  src/main/java/dan200/computercraft/core/apis/http/request/HttpRequestHandler.java
  src/main/java/dan200/computercraft/core/apis/http/websocket/WebsocketHandle.java
  src/main/java/dan200/computercraft/core/apis/http/websocket/WebsocketHandler.java
  src/main/java/dan200/computercraft/core/computer/Computer.java
  src/main/java/dan200/computercraft/core/computer/ComputerEnvironment.java
  src/main/java/dan200/computercraft/core/computer/ComputerExecutor.java
  src/main/java/dan200/computercraft/core/computer/Environment.java
  src/main/java/dan200/computercraft/core/computer/LuaContext.java
  src/main/java/dan200/computercraft/core/computer/MainThreadExecutor.java
  src/main/java/dan200/computercraft/core/lua/CobaltLuaMachine.java
  src/main/java/dan200/computercraft/core/lua/ILuaMachine.java
  src/main/java/dan200/computercraft/core/lua/MachineEnvironment.java
  src/main/java/dan200/computercraft/core/metrics/Metric.java
  src/main/java/dan200/computercraft/core/metrics/Metrics.java
  src/main/java/dan200/computercraft/core/metrics/MetricsObserver.java
  src/main/java/dan200/computercraft/core/tracking/ComputerMBean.java
  src/main/java/dan200/computercraft/core/tracking/ComputerTracker.java
  src/main/java/dan200/computercraft/core/tracking/Tracker.java
  src/main/java/dan200/computercraft/core/tracking/Tracking.java
  src/main/java/dan200/computercraft/core/tracking/TrackingContext.java
  src/main/java/dan200/computercraft/core/tracking/TrackingField.java
  src/main/java/dan200/computercraft/shared/CommonHooks.java
  src/main/java/dan200/computercraft/shared/command/CommandComputerCraft.java
  src/main/java/dan200/computercraft/shared/command/arguments/ArgumentSerializers.java
  src/main/java/dan200/computercraft/shared/command/arguments/TrackingFieldArgumentType.java
  src/main/java/dan200/computercraft/shared/computer/core/ServerComputer.java
  src/main/java/dan200/computercraft/shared/computer/core/ServerContext.java
  src/main/java/dan200/computercraft/shared/computer/metrics/ComputerMBean.java
  src/main/java/dan200/computercraft/shared/computer/metrics/ComputerMetricsObserver.java
  src/main/java/dan200/computercraft/shared/computer/metrics/GlobalMetrics.java
  src/main/java/dan200/computercraft/shared/computer/metrics/basic/Aggregate.java
  src/main/java/dan200/computercraft/shared/computer/metrics/basic/AggregatedMetric.java
  src/main/java/dan200/computercraft/shared/computer/metrics/basic/BasicComputerMetricsObserver.java
  src/main/java/dan200/computercraft/shared/computer/metrics/basic/ComputerMetrics.java
  src/main/java/dan200/computercraft/shared/turtle/apis/TurtleAPI.java
  src/main/resources/assets/computercraft/lang/en_us.json
  src/test/java/dan200/computercraft/core/apis/AsyncRunner.kt
  src/test/java/dan200/computercraft/core/computer/BasicEnvironment.java
  src/test/java/dan200/computercraft/core/computer/FakeComputerManager.java
Labels: enhancement, area-Core, area-Minecraft

#1190 Handle file transfers inside CraftOS
  doc/events/file_transfer.md
  gradle/libs.versions.toml
  src/main/java/dan200/computercraft/ComputerCraft.java
  src/main/java/dan200/computercraft/client/gui/ComputerScreenBase.java
  src/main/java/dan200/computercraft/client/gui/ItemToast.java
  src/main/java/dan200/computercraft/core/apis/handles/ByteBufferChannel.java
  src/main/java/dan200/computercraft/core/filesystem/ResourceMount.java
  src/main/java/dan200/computercraft/shared/Config.java
  src/main/java/dan200/computercraft/shared/command/CommandComputerCraft.java
  src/main/java/dan200/computercraft/shared/computer/blocks/TileComputerBase.java
  src/main/java/dan200/computercraft/shared/computer/inventory/ContainerComputerBase.java
  src/main/java/dan200/computercraft/shared/computer/menu/ServerInputHandler.java
  src/main/java/dan200/computercraft/shared/computer/menu/ServerInputState.java
  src/main/java/dan200/computercraft/shared/computer/upload/TransferredFile.java
  src/main/java/dan200/computercraft/shared/computer/upload/TransferredFiles.java
  src/main/java/dan200/computercraft/shared/computer/upload/UploadResult.java
  src/main/java/dan200/computercraft/shared/network/NetworkHandler.java
  src/main/java/dan200/computercraft/shared/network/client/UploadResultMessage.java
  src/main/java/dan200/computercraft/shared/network/container/ComputerContainerData.java
  src/main/java/dan200/computercraft/shared/network/server/ContinueUploadMessage.java
  src/main/java/dan200/computercraft/shared/pocket/items/ItemPocketComputer.java
  src/main/resources/assets/computercraft/lang/en_us.json
  src/main/resources/data/computercraft/lua/rom/apis/textutils.lua
  src/main/resources/data/computercraft/lua/rom/modules/internal/cc/import.lua
  src/main/resources/data/computercraft/lua/rom/programs/advanced/multishell.lua
  src/main/resources/data/computercraft/lua/rom/programs/import.lua
  src/main/resources/data/computercraft/lua/rom/programs/shell.lua
  src/test/java/dan200/computercraft/support/CustomMatchers.java
  src/test/resources/test-rom/spec/programs/shell_spec.lua
Labels: enhancement, feedback wanted, area-CraftOS, area-Documentation

#1193 Add `peripheral_hub` type for wired-modem-like peripherals
  src/main/java/dan200/computercraft/shared/peripheral/modem/wired/WiredModemPeripheral.java
  src/main/resources/data/computercraft/lua/rom/apis/peripheral.lua
Labels: enhancement, feedback wanted, area-CraftOS

#1195 Don't unnecessarily scroll in edit run wrapper
  src/main/resources/data/computercraft/lua/rom/programs/edit.lua
Labels: bug, area-CraftOS
