Repository cc-tweaked/CC-Tweaked, pull requests merged in 2022-12, with the labels that each got.

#1231 Time fs and peripheral operations
  projects/core/src/main/java/dan200/computercraft/core/apis/FSAPI.java
  projects/core/src/main/java/dan200/computercraft/core/apis/IAPIEnvironment.java
  projects/core/src/main/java/dan200/computercraft/core/apis/PeripheralAPI.java
  projects/core/src/main/java/dan200/computercraft/core/computer/Environment.java
  projects/core/src/main/java/dan200/computercraft/core/metrics/Metrics.java
  projects/core/src/main/java/dan200/computercraft/core/metrics/OperationTimer.java
  projects/core/src/test/java/dan200/computercraft/core/ComputerTestDelegate.java
  projects/core/src/testFixtures/java/dan200/computercraft/test/core/apis/BasicApiEnvironment.java
Labels: area-Core

#1262 Fix duplicated swing animations on high-ping servers
  projects/common/src/main/java/dan200/computercraft/shared/computer/blocks/AbstractComputerBlockEntity.java
  projects/common/src/main/java/dan200/computercraft/shared/media/items/PrintoutItem.java
  projects/common/src/main/java/dan200/computercraft/shared/peripheral/modem/wired/CableBlockEntity.java
  projects/common/src/main/java/dan200/computercraft/shared/peripheral/modem/wired/CableBlockItem.java
  projects/common/src/main/java/dan200/computercraft/shared/peripheral/modem/wired/WiredModemFullBlockEntity.java
  projects/common/src/main/java/dan200/computercraft/shared/peripheral/monitor/MonitorBlock.java
  projects/common/src/main/java/dan200/computercraft/shared/pocket/items/PocketComputerItem.java
  projects/common/src/main/java/dan200/computercraft/shared/turtle/blocks/TurtleBlockEntity.java
Labels: bug, area-Minecraft, good first issue

#1275 Fix crash on Fabric when attempting to use a non-fuel item as fuel.
  buildSrc/src/main/kotlin/cc-tweaked.java-convention.gradle.kts
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Turtle_Test.kt
  projects/common/src/testMod/resources/data/cctest/structures/turtle_test.refuel_fail.snbt
  projects/fabric/src/main/java/dan200/computercraft/shared/platform/PlatformHelperImpl.java
Labels: bug, area-Minecraft

#1276 Fix bug where turtle drops inventory when moving
  projects/common/src/main/java/dan200/computercraft/shared/turtle/blocks/TurtleBlock.java
  projects/common/src/main/java/dan200/computercraft/shared/turtle/blocks/TurtleBlockEntity.java
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Turtle_Test.kt
  projects/common/src/testMod/resources/data/cctest/structures/turtle_test.move_preserves_state.snbt
Labels: bug, area-Minecraft

#1277 Fix crash when turtle digs with a full inventory and any slot other than slot 1 is selected
  projects/common/src/main/java/dan200/computercraft/shared/util/InventoryUtil.java
  projects/common/src/test/java/dan200/computercraft/shared/util/InventoryUtilTest.java
Labels: bug, area-Minecraft
