Repository cc-tweaked/CC-Tweaked, pull requests merged in 2022-07, with the labels that each got.

#1126 Spelling error Turtle API
  src/main/java/dan200/computercraft/shared/turtle/apis/TurtleAPI.java
Labels: bug, area-Documentation

#1112 Add WAV support to speaker.lua
  src/main/resources/data/computercraft/lua/rom/programs/fun/speaker.lua
Labels: enhancement, area-CraftOS

#1127 ItemGroup info on getItemDetail
  src/main/java/dan200/computercraft/shared/peripheral/generic/data/ItemData.java
  src/main/java/dan200/computercraft/shared/peripheral/generic/methods/InventoryMethods.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: enhancement, area-Minecraft

#1139 Clearify GPS documentation note
  src/main/resources/data/computercraft/lua/rom/apis/gps.lua
Labels: enhancement, area-Documentation
