Repository cc-tweaked/CC-Tweaked, pull requests merged in 2022-05, with the labels that each got.

#1071 Add documentation on full list of 5.2/5.3 features
  doc/events/mouse_click.md
  doc/guides/feature_compat.md
  src/main/resources/data/computercraft/lua/rom/apis/colors.lua
  src/web/styles.css
Labels: enhancement, area-Documentation

#1083 [1.16] Make blocks rotatable for structures
  gradle.properties
  src/main/java/dan200/computercraft/shared/computer/blocks/BlockComputer.java
  src/main/java/dan200/computercraft/shared/peripheral/diskdrive/BlockDiskDrive.java
  src/main/java/dan200/computercraft/shared/peripheral/modem/wireless/BlockWirelessModem.java
  src/main/java/dan200/computercraft/shared/peripheral/monitor/BlockMonitor.java
  src/main/java/dan200/computercraft/shared/peripheral/printer/BlockPrinter.java
  src/main/java/dan200/computercraft/shared/peripheral/speaker/BlockSpeaker.java
  src/main/java/dan200/computercraft/shared/turtle/blocks/BlockTurtle.java
  src/main/resources/META-INF/mods.toml
Labels: enhancement, area-Minecraft

#1058 Add note about special JSON values in docs for `textutils.unserializeJSON`
  src/main/resources/data/computercraft/lua/rom/apis/textutils.lua
Labels: enhancement, area-Documentation

#1095 Add important leading /
  src/main/resources/data/computercraft/lua/rom/programs/edit.lua
Labels: bug, area-CraftOS

#1099 Add validation to printer slots
  src/main/java/dan200/computercraft/shared/peripheral/printer/ContainerPrinter.java
  src/main/java/dan200/computercraft/shared/peripheral/printer/TilePrinter.java
  src/main/java/dan200/computercraft/shared/util/ValidatingSlot.java
Labels: enhancement, area-Minecraft
