Repository cc-tweaked/CC-Tweaked, pull requests merged in 2023-01, with the labels that each got.

#1295 Read computer threads directly from the config object
  gradle/libs.versions.toml
  projects/common/src/main/java/dan200/computercraft/shared/computer/core/ServerContext.java
  projects/common/src/main/java/dan200/computercraft/shared/config/Config.java
  projects/common/src/main/java/dan200/computercraft/shared/config/ConfigSpec.java
  projects/fabric/src/main/java/dan200/computercraft/shared/ComputerCraft.java
Labels: bug, area-Core, area-Minecraft

#1273 Add support for shebangs, closes #551
  projects/core/src/main/resources/data/computercraft/lua/rom/programs/shell.lua
  projects/core/src/test/resources/test-rom/spec/programs/shell_spec.lua
Labels: enhancement, area-CraftOS

#1304 Update event docs
  doc/events/computer_command.md
  doc/events/redstone.md
  doc/events/task_complete.md
  doc/events/term_resize.md
  doc/events/terminate.md
  doc/events/turtle_inventory.md
Labels: enhancement, area-Documentation

#1298 Better Lua parse errors
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/internal/error_printer.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/internal/syntax/errors.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/internal/syntax/init.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/internal/syntax/lexer.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/internal/syntax/parser.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/programs/edit.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/programs/lua.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/programs/shell.lua
  projects/core/src/test/resources/test-rom/spec/modules/cc/internal/syntax/init_spec.lua
  projects/core/src/test/resources/test-rom/spec/modules/cc/internal/syntax/lexer_spec.md
  projects/core/src/test/resources/test-rom/spec/modules/cc/internal/syntax/parser_exhaustive_spec.md
  projects/core/src/test/resources/test-rom/spec/modules/cc/internal/syntax/parser_spec.md
  projects/core/src/test/resources/test-rom/spec/modules/cc/internal/syntax/syntax_helpers.lua
  projects/core/src/test/resources/test-rom/spec/test_helpers.lua
Labels: enhancement, feedback wanted, area-CraftOS
