Repository cc-tweaked/CC-Tweaked, pull requests merged in 2023-08, with the labels that each got.

#1549 Typo `instealled` -> `installed` and some grammar "improvements"
  CONTRIBUTING.md
Labels: area-Documentation

#1558 Add dark mode styling for recipes
  projects/web/src/styles.css
Labels: enhancement, area-Documentation

#1559 Documentation: Fix wrong function being named
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/image/nft.lua
Labels: bug, area-Documentation

#1564 Fixed documentation: Turtle API in case of dropDown method
  projects/common/src/main/java/dan200/computercraft/shared/turtle/apis/TurtleAPI.java
Labels: bug, area-Documentation

#1569 Remove compression from terminal/monitor packets
  projects/common/src/main/java/dan200/computercraft/shared/computer/terminal/TerminalState.java
  projects/common/src/test/java/dan200/computercraft/shared/computer/terminal/TerminalStateTest.java
Labels: enhancement, area-Minecraft

#1572 Move GUI textures to a sprite sheet
  projects/common/src/client/java/dan200/computercraft/client/ClientRegistry.java
  projects/common/src/client/java/dan200/computercraft/client/gui/ComputerScreen.java
  projects/common/src/client/java/dan200/computercraft/client/gui/GuiSprites.java
  projects/common/src/client/java/dan200/computercraft/client/gui/TurtleScreen.java
  projects/common/src/client/java/dan200/computercraft/client/gui/widgets/ComputerSidebar.java
  projects/common/src/client/java/dan200/computercraft/client/gui/widgets/DynamicImageButton.java
  projects/common/src/client/java/dan200/computercraft/client/render/ComputerBorderRenderer.java
  projects/common/src/client/java/dan200/computercraft/client/render/PocketItemRenderer.java
  projects/common/src/client/java/dan200/computercraft/client/render/RenderTypes.java
  projects/common/src/client/java/dan200/computercraft/client/render/SpriteRenderer.java
  projects/common/src/client/java/dan200/computercraft/data/client/ClientDataProviders.java
  projects/common/src/main/resources/assets/computercraft/textures/gui/border_advanced.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/border_colour.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/border_command.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/border_normal.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons/terminate.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons/terminate_hover.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons/turned_off.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons/turned_off_hover.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons/turned_on.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/buttons/turned_on_hover.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/corners_advanced.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/corners_colour.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/corners_command.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/corners_normal.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/pocket_bottom_advanced.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/pocket_bottom_colour.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/pocket_bottom_normal.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/sidebar_advanced.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/sidebar_command.png
  projects/common/src/main/resources/assets/computercraft/textures/gui/sidebar_normal.png
  projects/fabric/src/client/java/dan200/computercraft/mixin/client/MinecraftMixin.java
  projects/fabric/src/generated/resources/assets/computercraft/atlases/gui.json
  projects/forge/src/client/java/dan200/computercraft/client/ForgeClientRegistry.java
  projects/forge/src/generated/resources/assets/computercraft/atlases/gui.json
  tools/update-resources.py
Labels: enhancement, area-Minecraft
