Repository cc-tweaked/CC-Tweaked, pull requests merged in 2024-03, with the labels that each got.

#1763 Fix cc.image.nft.draw signature
  projects/core/src/main/resources/data/computercraft/lua/rom/modules/main/cc/image/nft.lua
Labels: bug, area-Documentation

#1761 Prevent playing music discs with speaker.playSound
  projects/common/src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPeripheral.java
  projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Speaker_Test.kt
  projects/common/src/testMod/resources/data/cctest/structures/speaker_test.will_not_play_record.snbt
Labels: enhancement, feedback wanted, area-Minecraft

#1747 `speaker sound` command
  projects/core/src/main/resources/data/computercraft/lua/rom/programs/fun/speaker.lua
  projects/core/src/main/resources/data/computercraft/lua/rom/startup.lua
Labels: enhancement, area-CraftOS
